<a href="https://colab.research.google.com/github/hrushikesh01/AIML-2024-25/blob/main/Lab2%20Part%203.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import heapq
from itertools import count


goal_state = np.array([[1, 2, 3],
                       [8, 0, 4],
                       [7, 6, 5]])


def heuristic(state):
    distance = 0
    for i in range(3):
        for j in range(3):
            value = state[i, j]
            if value != 0:
                goal_position = np.argwhere(goal_state == value)[0]
                distance += abs(goal_position[0] - i) + abs(goal_position[1] - j)
    return distance


def find_zero(state):
    return np.argwhere(state == 0)[0]


def get_neighbors(state):
    neighbors = []
    zero_pos = find_zero(state)
    moves = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    for move in moves:
        new_zero_pos = zero_pos + move
        if 0 <= new_zero_pos[0] < 3 and 0 <= new_zero_pos[1] < 3:
            new_state = state.copy()
            new_state[zero_pos[0], zero_pos[1]] = state[new_zero_pos[0], new_zero_pos[1]]
            new_state[new_zero_pos[0], new_zero_pos[1]] = 0
            neighbors.append(new_state)

    return neighbors


def state_equals(state1, state2):
    return np.array_equal(state1, state2)


def reconstruct_path(came_from, current):
    path = [current]
    while tuple(map(tuple, current)) in came_from:
        current = came_from[tuple(map(tuple, current))]
        path.append(current)
    return path[::-1]


def a_star(initial_state):
    open_list = []
    closed_list = set()
    g_scores = {tuple(map(tuple, initial_state)): 0}
    heap_counter = count()
    heapq.heappush(open_list, (heuristic(initial_state), next(heap_counter), initial_state))

    came_from = {}

    while open_list:
        _, _, current = heapq.heappop(open_list)

        if state_equals(current, goal_state):
            path = reconstruct_path(came_from, current)
            return path

        closed_list.add(tuple(map(tuple, current)))

        for neighbor in get_neighbors(current):
            neighbor_tuple = tuple(map(tuple, neighbor))
            tentative_g_score = g_scores[tuple(map(tuple, current))] + 1

            if neighbor_tuple in closed_list:
                continue

            if neighbor_tuple not in g_scores or tentative_g_score < g_scores[neighbor_tuple]:
                came_from[neighbor_tuple] = current
                g_scores[neighbor_tuple] = tentative_g_score
                f_score = tentative_g_score + heuristic(neighbor)
                heapq.heappush(open_list, (f_score, next(heap_counter), neighbor))

    return None


initial_state = np.array([[2, 8, 3],
                          [1, 6, 4],
                          [7, 0, 5]])


path = a_star(initial_state)


if path:
    print("Steps to reach goal:", len(path) - 1)
    print("Total nodes visited:", len(path))
    for state in path:
        print(state, "\n")
else:
    print("No solution found")

Steps to reach goal: 5
Total nodes visited: 6
[[2 8 3]
 [1 6 4]
 [7 0 5]] 

[[2 8 3]
 [1 0 4]
 [7 6 5]] 

[[2 0 3]
 [1 8 4]
 [7 6 5]] 

[[0 2 3]
 [1 8 4]
 [7 6 5]] 

[[1 2 3]
 [0 8 4]
 [7 6 5]] 

[[1 2 3]
 [8 0 4]
 [7 6 5]] 

